[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add form handling success redirect
[[redirects]]
  from = "/success"
  to = "/thank-you"
  status = 301
